# Generated by Django 3.2.8 on 2021-10-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_portfolio_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
