# Generated by Django 3.2.8 on 2021-10-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill_is_framework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='is_framework',
        ),
    ]
