# Generated by Django 3.2.8 on 2021-11-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_skill_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
